/*Sub Consultas*/
SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COD_PROD IN (SELECT TVD.COD_PROD
					  FROM dbo.tblVentas_Detalle TVD
					  WHERE TVD.CANTIDAD > 200)

SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COS_PROM_C >= (SELECT AVG(TP2.COS_PROM_C) FROM dbo.tblProductos TP2)

/*ALL (EN CASO DE TENER MAS DE 1 RESPUESTA EN LA SUBCONSULTA)*/
SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COS_PROM_C >ALL (SELECT TOP 2 TP2.COS_PROM_C FROM dbo.tblProductos TP2)
ORDER BY TP.COS_PROM_C

/*ANY (EN CASO DE TENER MAS DE 1 RESPUESTA EN LA SUBCONSULTA)*/
SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COS_PROM_C <ANY (SELECT TOP 2 TP2.COS_PROM_C FROM dbo.tblProductos TP2)
ORDER BY TP.COS_PROM_C DESC


/*EXISTS AND NO EXISTS VALIDA SUB CONSULTAS*/
SELECT *
FROM dbo.tblClientes TC
WHERE NOT EXISTS(SELECT * FROM tblVentas TV WHERE TV.COD_ID = TC.COD_ID)

/*HAVING*/
SELECT TP.MARCA,
	   AVG(TP.PRECIO_VTA) AS PROMEDIO_VTA
FROM dbo.tblProductos TP
GROUP BY TP.MARCA
HAVING AVG(TP.PRECIO_VTA) > (SELECT AVG(TP2.PRECIO_VTA) FROM dbo.tblProductos TP2)
ORDER BY PROMEDIO_VTA DESC

/*TABLA DERIVADA*/
SELECT TV.*, TOP_VENTAS.TOTAL_VENTA
FROM dbo.tblVentas TV
INNER JOIN(
			SELECT TOP 10 TVD.ID,
				   SUM(TVD.CANTIDAD * TVD.VALOR) AS TOTAL_VENTA
			FROM dbo.tblVentas_Detalle TVD
			GROUP BY TVD.ID
			ORDER BY TOTAL_VENTA DESC
			) AS TOP_VENTAS ON TV.ID=TOP_VENTAS.ID

/*SUB CONSULTA SELECT (NO RECOMENDABLE POR PERFORMANCE)*/
SELECT TV.ID,
	   TV.COD_SUC,
	   (SELECT TS.Sucursal FROM dbo.tblSucursales TS WHERE TS.COD_SUC = TV.COD_SUC COLLATE DATABASE_DEFAULT) AS NOM_SUC,
	   TV.NUM_DOC,
	   TV.CONDICIONES,
	   (SELECT TC.NOMBRE FROM dbo.tblClientes TC WHERE TC.COD_ID=TV.COD_ID) AS NOMBRE_CLIENTE
FROM dbo.tblVentas TV

/*CTE*/
WITH CTE_RESUMEN
AS
(
	SELECT TV.COD_SUC,
		   TV.COD_ID,
		   SUM(TVD.CANTIDAD * TVD.VALOR) AS TOTAL_VENTA
	FROM dbo.tblVentas TV INNER JOIN tblVentas_Detalle TVD ON TV.ID = TVD.ID
	WHERE TV.FECHA BETWEEN '2014/01/01' AND '2015/12/01'
	GROUP BY TV.COD_SUC, TV.COD_ID
),
CTE_MAX
AS
(
	SELECT CR.COD_SUC,
	       MAX(CR.TOTAL_VENTA) AS TOTAL_VENTA
	FROM CTE_RESUMEN CR
	GROUP BY CR.COD_SUC
)
SELECT CR.COD_SUC,TS.Sucursal AS SUCURSAL,CR.COD_ID,TC.NOMBRE AS CLIENTE,CM.TOTAL_VENTA
FROM CTE_RESUMEN CR
INNER JOIN CTE_MAX CM ON CR.COD_SUC = CM.COD_SUC AND CR.TOTAL_VENTA =CM.TOTAL_VENTA
INNER JOIN dbo.tblClientes TC ON CR.COD_ID = TC.COD_ID COLLATE DATABASE_DEFAULT
INNER JOIN dbo.tblSucursales TS ON CR.COD_SUC = TS.COD_SUC COLLATE DATABASE_DEFAULT
ORDER BY CR.COD_SUC