/*Sub Consultas*/
SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COD_PROD IN (SELECT TVD.COD_PROD
					  FROM dbo.tblVentas_Detalle TVD
					  WHERE TVD.CANTIDAD > 200)

SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COS_PROM_C >= (SELECT AVG(TP2.COS_PROM_C) FROM dbo.tblProductos TP2)

/*ALL (EN CASO DE TENER MAS DE 1 RESPUESTA EN LA SUBCONSULTA)*/
SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COS_PROM_C >ALL (SELECT TOP 2 TP2.COS_PROM_C FROM dbo.tblProductos TP2)
ORDER BY TP.COS_PROM_C

/*ANY (EN CASO DE TENER MAS DE 1 RESPUESTA EN LA SUBCONSULTA)*/
SELECT TP.*
FROM dbo.tblProductos TP
WHERE TP.COS_PROM_C <ANY (SELECT TOP 2 TP2.COS_PROM_C FROM dbo.tblProductos TP2)
ORDER BY TP.COS_PROM_C DESC