/*1.Funciones de Cadena LEN,LEFT,RIGHT,LTRIM, RTRIM, LOWER,UPPER,PATINDEX, CHARINDEX,SUBSTRING,REPLACE,REVERSE,CONCAT*/

DECLARE @VARIABLE VARCHAR(50)='SQL Server',
        @VARIABLE2 VARCHAR(50)='   SQL Server   '

SELECT LEN(@VARIABLE) AS LONGITUDDECADENA,
       LEFT(@VARIABLE,3) AS CARACTERESALAIZQUIERDA,
	   RIGHT(@VARIABLE,3) AS CARACTERESALADERECHA,
	   LTRIM(@VARIABLE2) AS QUITARESPACIOSALAIZQUIERDA,
	   RTRIM(@VARIABLE2) AS QUITARESPACIOSALADERECHA,
	   LOWER(@VARIABLE) AS CONVERTIRAMINUSCULA,
	   UPPER(@VARIABLE) AS CONVERTIRAMAYUSCULA,
	   CHARINDEX('SQL',@VARIABLE2) AS ENCONTRARPOSICION,
	   PATINDEX('%v_r%',@VARIABLE) AS ENCONTRARPOSICION2,
	   SUBSTRING(@VARIABLE,1,LEN(@VARIABLE)-LEN(LEFT(@VARIABLE,3))-3) AS EXTRAERCARACTERES,
	   REPLACE(@VARIABLE,'server','SERVER 2016') AS REEMPLAZACADENA,
	   REVERSE(@VARIABLE) AS CADENAALREVES,
	   CONCAT(@VARIABLE,SPACE(2),GETDATE(),NULL,2018) AS FUNCIONCONCAT
	   

/*2.Funcines Numericas ROUND,ISNUMERIC,ABS,CEILING,FLOOR,SQUARE,SQRT,RAND*/
SELECT ROUND(12.5,0) AS ROUND1,
       ROUND(12.49999,0) AS ROUND2,
	   ISNUMERIC(85) AS ISNUMERIC1,
	   ISNUMERIC('SQL') AS ISNUMERIC2,
	   ABS(-25) AS ABS1,
	   CEILING(1.25) AS CEILING1,
	   FLOOR(1.25) FLOOR1,
	   SQUARE(5) AS SQUARE1,
	   SQRT(2) AS SQRT1,
	   RAND() AS RAND1

/*Funciones de Fecha*/
SELECT TOP 1 day(tv.fecha)                 AS DIA1,
             MONTH(TV.FECHA)               AS MES1,
			 YEAR(TV.FECHA)                AS ANNO1,
			 EOMONTH(TV.FECHA)             AS FINDEMES,
			 DATEPART(DD,TV.FECHA)         AS DIA2,
			 DATEPART(HOUR,GETDATE())      AS HORA1,
             DATEPART(minute,getdate())    AS MINUTO1,
			 datepart(quarter,getdate())   AS TRIMESTRE1,
			 datepart(dayofyear,getdate()) AS DIASTRANSCURRIDOS,
			 datepart(week,getdate())      AS NUMEROSEMANA,
	         datename(month,getdate())     AS NOMBREMES,
			 datename(weekday,getdate())   AS DIAACTUAL
from tblVentas tv

/*Funciones de Fecha II*/
SELECT TOP 1 tv.FECHA AS                FECHAFACTURA,
            DATEADD(day,30,tv.fecha)        AS DAYADD1,
			DATEADD(year,1,tv.fecha)        AS DAYADD2,
			DATEADD(year,-1,tv.fecha)       AS DAYADD2 ,
            DATEDIFF(day,tv.fecha,getdate()) AS DATEDIFF1,
			DATEDIFF(year,tv.fecha,getdate()) AS DATEDIFF2 ,
			DATEDIFF(minute,'06:00:00',CAST(getdate() AS TIME)) AS DATEDIFF3
from tblVentas tv