/*Funcion de agregacion COUNT MIN MAX SUM AVG*/
SELECT COUNT(*) AS CANTIDAD_TOTAL,
	   MIN(TP.PRECIO_VTA) AS PRECIO_MINIMO,
	   MAX(TP.PRECIO_VTA) AS PRECIO_MAXIMO,
	   CAST(SUM(TP.PRECIO_VTA) AS NUMERIC(18,2)) AS SUMA_TOTAL_PRECIO_VTA,
	   CAST(AVG(TP.PRECIO_VTA) AS NUMERIC(18,2)) AS PRECIO_PROMEDIO
FROM dbo.tblProductos TP