/*Funcion de agregacion COUNT MIN MAX SUM AVG*/
SELECT COUNT(*) AS CANTIDAD_TOTAL,
	   MIN(TP.PRECIO_VTA) AS PRECIO_MINIMO,
	   MAX(TP.PRECIO_VTA) AS PRECIO_MAXIMO,
	   CAST(SUM(TP.PRECIO_VTA) AS NUMERIC(18,2)) AS SUMA_TOTAL_PRECIO_VTA,
	   CAST(AVG(TP.PRECIO_VTA) AS NUMERIC(18,2)) AS PRECIO_PROMEDIO
FROM dbo.tblProductos TP

/*GROUP BY*/

SELECT TV.COD_SUC,
	   MAX(TVD.CANTIDAD * TVD.COSTO) AS MAX_VENTA_SUC,
	   MIN(TVD.CANTIDAD * TVD.COSTO) AS MIN_VENTA_SUC,
	   MAX(TV.FECHA) AS ULTIMA_VENTA,
	   MIN(TV.FECHA) AS PRIMERA_VENTA,
	   COUNT(*) AS TOTAL_REGISTROS_SUC,
	   AVG(TVD.CANTIDAD * TVD.COSTO) AS VENTA_PROMEDIO
FROM dbo.tblVentas TV
INNER JOIN dbo.tblVentas_Detalle TVD ON TV.ID=TVD.ID
GROUP BY TV.COD_SUC

/*WITH ROLLUP*/
SELECT COUNT(*) OVER(ORDER BY TL.NOM_LIN DESC) AS N,
	   TL.NOM_LIN,
	   SUM(TVD.CANTIDAD * TVD.COSTO) AS TOTAL_COSTO,
	   SUM(TVD.CANTIDAD * TVD.VALOR) AS TOTAL_VENTA,
	   SUM(TVD.CANTIDAD * TVD.VALOR - TVD.CANTIDAD * TVD.COSTO) AS TOTAL_UTILIDAD,
	   ROUND(SUM(TVD.CANTIDAD * TVD.VALOR - TVD.CANTIDAD * TVD.COSTO)/SUM(TVD.CANTIDAD * TVD.VALOR) * 100, 0) AS PORCENTAJE_UTILIDAD
--INTO #TMP_PORCENTAJE
FROM dbo.tblVentas TV
INNER JOIN dbo.tblVentas_Detalle TVD ON TV.ID = TVD.ID
INNER JOIN dbo.tblProductos TP ON TVD.COD_PROD = TP.COD_PROD
INNER JOIN dbo.tblLineas TL ON TP.COD_LIN = TL.COD_LIN
WHERE TV.FECHA BETWEEN '2014/01/01' AND '2014/12/31'
GROUP BY TL.NOM_LIN --WITH ROLLUP
--HAVING ROUND(SUM(TVD.CANTIDAD * TVD.VALOR - TVD.CANTIDAD * TVD.COSTO)/SUM(TVD.CANTIDAD * TVD.VALOR) * 100,0) < 20

SELECT NOM_LIN,
	   SUM(TOTAL_COSTO) AS TOTAL_COSTO,
	   SUM(TOTAL_VENTA) AS TOTAL_VENTA,
	   SUM(TOTAL_UTILIDAD) AS TOTAL_UTILIDAD,
	   SUM(PORCENTAJE_UTILIDAD) AS PORCENTAJE
FROM #TMP_PORCENTAJE
GROUP BY NOM_LIN WITH ROLLUP
--HAVING NOM_LIN IS NULL 

/*Acumulacion de ventas*/

WITH CTE_VENTAS
AS(
	SELECT COUNT(*) OVER(ORDER BY TL.NOM_LIN DESC) AS N,
	TL.NOM_LIN,
	SUM(TVD.CANTIDAD * TVD.COSTO) AS TOTAL_COSTO,
	SUM(TVD.CANTIDAD * TVD.VALOR) AS TOTAL_VENTA
	FROM dbo.tblVentas TV
	INNER JOIN dbo.tblVentas_Detalle TVD ON TV.ID = TVD.ID
	INNER JOIN dbo.tblProductos TP ON TVD.COD_PROD = TP.COD_PROD
	INNER JOIN dbo.tblLineas TL ON TP.COD_LIN = TL.COD_LIN
	WHERE TV.FECHA BETWEEN '2014/01/01' AND '2015/12/31'
	GROUP BY NOM_LIN
)
SELECT CV.NOM_LIN,
	   CV.TOTAL_VENTA,
	   SUM(SUM(CV.TOTAL_VENTA)) OVER(ORDER BY CV.NOM_LIN ASC) AS ACUMULADO
FROM CTE_VENTAS CV
GROUP BY CV.NOM_LIN,CV.TOTAL_VENTA

/*Group sets*/

SELECT TP.COD_LIN,MARCA,
	   COUNT(*) AS CANTIDAD_PRODUCTOS
FROM dbo.tblProductos TP
WHERE TP.COD_LIN IN ('003','004')
GROUP BY GROUPING SETS(TP.COD_LIN,TP.MARCA)
ORDER BY TP.COD_LIN DESC,TP.MARCA DESC